"""init ledger

Revision ID: 0c1e6476d8ef
Revises: 
Create Date: 2026-01-15 22:34:51.589439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c1e6476d8ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('subscription_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subscription_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_code'), 'company', ['code'], unique=True)
    op.create_index(op.f('ix_company_company_id'), 'company', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_table('currency',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    op.create_index(op.f('ix_currency_company_id'), 'currency', ['company_id'], unique=False)
    op.create_index(op.f('ix_currency_id'), 'currency', ['id'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('external_customer_ref', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('kyc_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('metadata_', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_company_id'), 'customer', ['company_id'], unique=False)
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_table('paymentprovider',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provider_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endpoint_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_paymentprovider_company_id'), 'paymentprovider', ['company_id'], unique=False)
    op.create_index(op.f('ix_paymentprovider_id'), 'paymentprovider', ['id'], unique=False)
    op.create_table('securityuser',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securityuser_company_id'), 'securityuser', ['company_id'], unique=False)
    op.create_index(op.f('ix_securityuser_email'), 'securityuser', ['email'], unique=True)
    op.create_index(op.f('ix_securityuser_id'), 'securityuser', ['id'], unique=False)
    op.create_index(op.f('ix_securityuser_is_active'), 'securityuser', ['is_active'], unique=False)
    op.create_index(op.f('ix_securityuser_username'), 'securityuser', ['username'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_company_id'), 'user', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('owner_customer_id', sa.Uuid(), nullable=True),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('account_category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('locked_balance', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['owner_customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_index(op.f('ix_account_company_id'), 'account', ['company_id'], unique=False)
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.create_table('auditlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('entity', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('changes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_company_id'), 'auditlog', ['company_id'], unique=False)
    op.create_index(op.f('ix_auditlog_id'), 'auditlog', ['id'], unique=False)
    op.create_table('exchangerate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('base_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('quote_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_currency'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['quote_currency'], ['currency.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchangerate_base_currency'), 'exchangerate', ['base_currency'], unique=False)
    op.create_index(op.f('ix_exchangerate_company_id'), 'exchangerate', ['company_id'], unique=False)
    op.create_index(op.f('ix_exchangerate_id'), 'exchangerate', ['id'], unique=False)
    op.create_index(op.f('ix_exchangerate_quote_currency'), 'exchangerate', ['quote_currency'], unique=False)
    op.create_table('externaltransaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('provider_transaction_ref', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['paymentprovider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_externaltransaction_company_id'), 'externaltransaction', ['company_id'], unique=False)
    op.create_index(op.f('ix_externaltransaction_id'), 'externaltransaction', ['id'], unique=False)
    op.create_index(op.f('ix_externaltransaction_provider_id'), 'externaltransaction', ['provider_id'], unique=False)
    op.create_index(op.f('ix_externaltransaction_provider_transaction_ref'), 'externaltransaction', ['provider_transaction_ref'], unique=False)
    op.create_table('journal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_debit', sa.Float(), nullable=False),
    sa.Column('total_credit', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currency.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_journal_company_id'), 'journal', ['company_id'], unique=False)
    op.create_index(op.f('ix_journal_id'), 'journal', ['id'], unique=False)
    op.create_table('loan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('loan_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('principal_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('metadata_', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_number')
    )
    op.create_index(op.f('ix_loan_company_id'), 'loan', ['company_id'], unique=False)
    op.create_index(op.f('ix_loan_customer_id'), 'loan', ['customer_id'], unique=False)
    op.create_index(op.f('ix_loan_id'), 'loan', ['id'], unique=False)
    op.create_table('reconciliation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('total_debits', sa.Integer(), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('balanced', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('calculated_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['calculated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_balanced'), 'reconciliation', ['balanced'], unique=False)
    op.create_index(op.f('ix_reconciliation_business_date'), 'reconciliation', ['business_date'], unique=False)
    op.create_index(op.f('ix_reconciliation_company_id'), 'reconciliation', ['company_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_id'), 'reconciliation', ['id'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('plan_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('provider_subscription_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['paymentprovider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_company_id'), 'subscription', ['company_id'], unique=False)
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    op.create_table('fee',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('loan_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_company_id'), 'fee', ['company_id'], unique=False)
    op.create_index(op.f('ix_fee_id'), 'fee', ['id'], unique=False)
    op.create_index(op.f('ix_fee_loan_id'), 'fee', ['loan_id'], unique=False)
    op.create_table('loanschedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_due', sa.Float(), nullable=False),
    sa.Column('interest_due', sa.Float(), nullable=False),
    sa.Column('total_due', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('metadata_', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loanschedule_company_id'), 'loanschedule', ['company_id'], unique=False)
    op.create_index(op.f('ix_loanschedule_id'), 'loanschedule', ['id'], unique=False)
    op.create_index(op.f('ix_loanschedule_loan_id'), 'loanschedule', ['loan_id'], unique=False)
    op.create_table('posting',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('journal_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('entry_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posting_account_id'), 'posting', ['account_id'], unique=False)
    op.create_index(op.f('ix_posting_company_id'), 'posting', ['company_id'], unique=False)
    op.create_index(op.f('ix_posting_id'), 'posting', ['id'], unique=False)
    op.create_index(op.f('ix_posting_journal_id'), 'posting', ['journal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posting_journal_id'), table_name='posting')
    op.drop_index(op.f('ix_posting_id'), table_name='posting')
    op.drop_index(op.f('ix_posting_company_id'), table_name='posting')
    op.drop_index(op.f('ix_posting_account_id'), table_name='posting')
    op.drop_table('posting')
    op.drop_index(op.f('ix_loanschedule_loan_id'), table_name='loanschedule')
    op.drop_index(op.f('ix_loanschedule_id'), table_name='loanschedule')
    op.drop_index(op.f('ix_loanschedule_company_id'), table_name='loanschedule')
    op.drop_table('loanschedule')
    op.drop_index(op.f('ix_fee_loan_id'), table_name='fee')
    op.drop_index(op.f('ix_fee_id'), table_name='fee')
    op.drop_index(op.f('ix_fee_company_id'), table_name='fee')
    op.drop_table('fee')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_company_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_reconciliation_id'), table_name='reconciliation')
    op.drop_index(op.f('ix_reconciliation_company_id'), table_name='reconciliation')
    op.drop_index(op.f('ix_reconciliation_business_date'), table_name='reconciliation')
    op.drop_index(op.f('ix_reconciliation_balanced'), table_name='reconciliation')
    op.drop_table('reconciliation')
    op.drop_index(op.f('ix_loan_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_customer_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_company_id'), table_name='loan')
    op.drop_table('loan')
    op.drop_index(op.f('ix_journal_id'), table_name='journal')
    op.drop_index(op.f('ix_journal_company_id'), table_name='journal')
    op.drop_table('journal')
    op.drop_index(op.f('ix_externaltransaction_provider_transaction_ref'), table_name='externaltransaction')
    op.drop_index(op.f('ix_externaltransaction_provider_id'), table_name='externaltransaction')
    op.drop_index(op.f('ix_externaltransaction_id'), table_name='externaltransaction')
    op.drop_index(op.f('ix_externaltransaction_company_id'), table_name='externaltransaction')
    op.drop_table('externaltransaction')
    op.drop_index(op.f('ix_exchangerate_quote_currency'), table_name='exchangerate')
    op.drop_index(op.f('ix_exchangerate_id'), table_name='exchangerate')
    op.drop_index(op.f('ix_exchangerate_company_id'), table_name='exchangerate')
    op.drop_index(op.f('ix_exchangerate_base_currency'), table_name='exchangerate')
    op.drop_table('exchangerate')
    op.drop_index(op.f('ix_auditlog_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_company_id'), table_name='auditlog')
    op.drop_table('auditlog')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_index(op.f('ix_account_company_id'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_company_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_securityuser_username'), table_name='securityuser')
    op.drop_index(op.f('ix_securityuser_is_active'), table_name='securityuser')
    op.drop_index(op.f('ix_securityuser_id'), table_name='securityuser')
    op.drop_index(op.f('ix_securityuser_email'), table_name='securityuser')
    op.drop_index(op.f('ix_securityuser_company_id'), table_name='securityuser')
    op.drop_table('securityuser')
    op.drop_index(op.f('ix_paymentprovider_id'), table_name='paymentprovider')
    op.drop_index(op.f('ix_paymentprovider_company_id'), table_name='paymentprovider')
    op.drop_table('paymentprovider')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_company_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_currency_id'), table_name='currency')
    op.drop_index(op.f('ix_currency_company_id'), table_name='currency')
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_table('currency')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_index(op.f('ix_company_company_id'), table_name='company')
    op.drop_index(op.f('ix_company_code'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
